//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chroma.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Animations/Spiral_Keyboard.chroma")]
        public string Portal {
            get {
                return ((string)(this["Portal"]));
            }
            set {
                this["Portal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Animations/OutParticle1_Keyboard.chroma")]
        public string Lifestone {
            get {
                return ((string)(this["Lifestone"]));
            }
            set {
                this["Lifestone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Animations/Arrow1_Keyboard.chroma")]
        public string Blank {
            get {
                return ((string)(this["Blank"]));
            }
            set {
                this["Blank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Animations/ParticlesOut_Keyboard.chroma")]
        public string Death {
            get {
                return ((string)(this["Death"]));
            }
            set {
                this["Death"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Animations/Llama1_Keyboard.chroma")]
        public string Spellcast {
            get {
                return ((string)(this["Spellcast"]));
            }
            set {
                this["Spellcast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Animations/CircleLarge_Keyboard.chroma")]
        public string Jump {
            get {
                return ((string)(this["Jump"]));
            }
            set {
                this["Jump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Animations/OutParticle1_Keyboard.chroma")]
        public string Emote {
            get {
                return ((string)(this["Emote"]));
            }
            set {
                this["Emote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Animations/Fork1_Keyboard.chroma")]
        public string RaiseSkill {
            get {
                return ((string)(this["RaiseSkill"]));
            }
            set {
                this["RaiseSkill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Animations/Bolt4_Keyboard.chroma")]
        public string TestAnim {
            get {
                return ((string)(this["TestAnim"]));
            }
            set {
                this["TestAnim"] = value;
            }
        }
    }
}
